---
author: Hristo Genev
timezone: Europe/Paris

date-parameter:
  format: yyyy-MM-dd

#
# https://www.bein.com/en/tv-guide/?c=bg
#
request:
  debug: false
  url: https://www.bein.com/en/epg-ajax-template/?action=epg_fetch&offset=0&category=sports&serviceidentity=bein.net&mins=00&cdate=${date}&language=EN&postid=25356&loadindex=0
  # headers:
  #   x-requested-with: XMLHttpRequest
  # body-params:
  #   action: epg_fetch
  #   offset: 0
  #   category: sports
  #   serviceidentity: bein.net
  #   mins: 00
  #   cdate: ${date}
  #   language: EN
  #   postid: 25356
  #   loadindex: 0

programs:
  locator: "#ul_slider_${channelId} li"
  exclude-first: 1
  
elements:
  - name: start
    locator: .time
    operations:
      - name: regex-extract
        hook: after
        debug: true
        arguments: [ "^(\\d{2}:\\d{2})" ]

  # - name: stop
  #   locator: .time
  #   operations:
  #     - name: regex-extract
  #       hook: after
  #       debug: true
  #       arguments: [ "(\\d{2}:\\d{2})$" ]
 
  - name: title
    locator: .onecontent

channel-parameters:    
  beinsports1.com:
    channelId: 1
  beinsports2.com:
    channelId: 2
  beinsports3.com:
    channelId: 3
  beinsports1.fr:
    channelId: 13
  beinsports2.fr:
    channelId: 14