---
version: 1.0
author: Hristo Genev

date-parameter:
  format: list
  debug: true
  list: [ 1,2,3,4,5,6,7 ]
  # The date-list-type can be absolute or relative. The default value if omitted is relative
  # Relative means, that values from date-list will be used from the first value on. If you 
  # started grabbing on Wednesday, then Wednesday will be 1, Thursday will be 2 etc.
  # Absolute means, that values from date-list will be used as per the current day of the week index
  # i.e. if today is Tuesday (the second day of the week), the grabber will use the second value from the date-list.
  # when it starts grabbing programs for the 3-rd day of the week, the 3-rd value will be used and so forth.
  list-type: absolute

week-overflow: false

request:
  url: https://rmtv.bg/programa
  debug: false

programs:
  locator: '#home-md${date} .d-block .justify-content-center'
  debug: false

elements:

  - name: start
    locator: h4
    debug: false

  - name: subtitle
    locator: h5

  - name: title
    locator: h3    
    operations:
      - name: append
        hook: after
        arguments: [ ' - ${subtitle}' ]
        conditions: [ argument-not-empty ]

